// OmniAgency OS - Realistic Seed Data for Multi-Tenant Relational Database

import {
  Agency,
  User,
  Team,
  TeamMember,
  Client,
  ClientUser,
  SocialAccount,
  Campaign,
  SocialPost,
  ContentDraft,
  ContentCalendarSlot,
  SeoProject,
  SeoKeyword,
  SeoIssue,
  AnalyticsRecord,
  Lead,
  Sale,
  Task,
  Report,
  Notification,
  Subscription,
  AuditLog,
} from '../types/database';

export const SEED_AGENCIES: Agency[] = [
  {
    id: 'agency-1',
    name: 'Nexus Social Global',
    slug: 'nexus-social',
    logo_url: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=150&auto=format&fit=crop&q=80',
    website: 'https://nexussocial.example.com',
    tier: 'enterprise',
    max_clients: 50,
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2026-03-01T12:00:00Z',
  },
  {
    id: 'agency-2',
    name: 'Vanguard Growth Labs',
    slug: 'vanguard-growth',
    logo_url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=150&auto=format&fit=crop&q=80',
    website: 'https://vanguardgrowth.example.com',
    tier: 'pro',
    max_clients: 20,
    created_at: '2025-06-15T09:30:00Z',
    updated_at: '2026-02-15T10:00:00Z',
  },
];

export const SEED_USERS: User[] = [
  {
    id: 'user-admin',
    agency_id: 'agency-1',
    email: 'elena@nexussocial.com',
    full_name: 'Elena Vance',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'SUPER_ADMIN',
    status: 'active',
    created_at: '2025-01-10T08:00:00Z',
    updated_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'user-cm',
    agency_id: 'agency-1',
    email: 'marcus@nexussocial.com',
    full_name: 'Marcus Ray',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'CONTENT_MANAGER',
    status: 'active',
    created_at: '2025-02-01T09:00:00Z',
    updated_at: '2026-02-10T00:00:00Z',
  },
  {
    id: 'user-team',
    agency_id: 'agency-1',
    email: 'chloe@nexussocial.com',
    full_name: 'Chloe Zhao',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'AGENCY_TEAM',
    status: 'active',
    created_at: '2025-03-12T11:00:00Z',
    updated_at: '2026-02-20T00:00:00Z',
  },
  {
    id: 'user-cust-1',
    agency_id: 'agency-1',
    email: 'david@luminaskin.com',
    full_name: 'David Chen',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'CUSTOMER',
    status: 'active',
    created_at: '2025-04-05T14:30:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-cust-2',
    agency_id: 'agency-1',
    email: 'sarah@apexfitness.com',
    full_name: 'Sarah Blake',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'CUSTOMER',
    status: 'active',
    created_at: '2025-05-18T10:15:00Z',
    updated_at: '2026-03-05T00:00:00Z',
  },
  {
    id: 'user-other-agency',
    agency_id: 'agency-2',
    email: 'julian@vanguardgrowth.com',
    full_name: 'Julian Moore',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    role: 'SUPER_ADMIN',
    status: 'active',
    created_at: '2025-06-15T09:30:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const SEED_TEAMS: Team[] = [
  {
    id: 'team-1',
    agency_id: 'agency-1',
    name: 'Growth & Creative Studio',
    description: 'Directs multi-channel content production, storytelling, and viral video creation.',
    created_at: '2025-01-15T08:00:00Z',
  },
  {
    id: 'team-2',
    agency_id: 'agency-1',
    name: 'Performance & Paid Media',
    description: 'Manages paid campaigns, attribution pipelines, ROAS tuning, and conversion funnels.',
    created_at: '2025-01-15T08:00:00Z',
  },
];

export const SEED_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    agency_id: 'agency-1',
    team_id: 'team-1',
    user_id: 'user-cm',
    role_in_team: 'lead',
    created_at: '2025-02-01T09:00:00Z',
  },
  {
    id: 'tm-2',
    agency_id: 'agency-1',
    team_id: 'team-2',
    user_id: 'user-team',
    role_in_team: 'member',
    created_at: '2025-03-12T11:00:00Z',
  },
];

export const SEED_CLIENTS: Client[] = [
  {
    id: 'client-1',
    agency_id: 'agency-1',
    name: 'Lumina Skin & Wellness',
    slug: 'lumina-skin',
    industry: 'Beauty & Skincare',
    website: 'https://luminaskin.example.com',
    brand_voice: 'Empathetic, scientific, luxurious, glowing, transparent',
    target_audience: 'Modern professionals aged 24-44 seeking clean, dermatologist-backed rituals',
    products_services: 'HydraGlow Serum, Botanical Ceramide Cream, SolarShield SPF 50',
    monthly_retainer: 8500,
    status: 'active',
    assigned_manager_id: 'user-cm',
    logo_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=150&auto=format&fit=crop&q=80',
    created_at: '2025-04-01T10:00:00Z',
    updated_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'client-2',
    agency_id: 'agency-1',
    name: 'Apex Fitness Gear',
    slug: 'apex-fitness',
    industry: 'Health & Athletic Apparel',
    website: 'https://apexfitness.example.com',
    brand_voice: 'Relentless, bold, performance-driven, high-energy, motivating',
    target_audience: 'CrossFit athletes, marathoners, strength trainers, high-performance fitness enthusiasts',
    products_services: 'Carbon-Grip Lifting Straps, AeroKnit Seamless Hoodies, Velocity Pro Kettlebells',
    monthly_retainer: 6500,
    status: 'active',
    assigned_manager_id: 'user-cm',
    logo_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=150&auto=format&fit=crop&q=80',
    created_at: '2025-05-15T11:00:00Z',
    updated_at: '2026-03-05T00:00:00Z',
  },
  {
    id: 'client-3',
    agency_id: 'agency-1',
    name: 'NovaCraft Coffee Roasters',
    slug: 'novacraft-coffee',
    industry: 'Specialty Food & Beverage',
    website: 'https://novacraftcoffee.example.com',
    brand_voice: 'Artisanal, cozy, grounded, sensory, eco-conscious',
    target_audience: 'Single-origin espresso lovers, pour-over hobbyists, sustainable lifestyle advocates',
    products_services: 'Ethiopian Yirgacheffe Beans, Cold Brew Concentrate Pods, Ceramic Drippers',
    monthly_retainer: 4500,
    status: 'active',
    assigned_manager_id: 'user-team',
    logo_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=150&auto=format&fit=crop&q=80',
    created_at: '2025-08-20T14:00:00Z',
    updated_at: '2026-02-28T00:00:00Z',
  },
  {
    id: 'client-isolated',
    agency_id: 'agency-2',
    name: 'HyperDrive SaaS',
    slug: 'hyperdrive-saas',
    industry: 'B2B Software',
    website: 'https://hyperdrive.example.com',
    brand_voice: 'Technical, crisp, enterprise',
    target_audience: 'CTOs and VP Engineering',
    products_services: 'Cloud Infrastructure Optimizer',
    monthly_retainer: 12000,
    status: 'active',
    created_at: '2025-07-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

export const SEED_CLIENT_USERS: ClientUser[] = [
  {
    id: 'cu-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-cust-1', // David Chen
    access_type: 'owner',
    created_at: '2025-04-05T14:30:00Z',
  },
  {
    id: 'cu-2',
    agency_id: 'agency-1',
    client_id: 'client-2',
    user_id: 'user-cust-2', // Sarah Blake
    access_type: 'owner',
    created_at: '2025-05-18T10:15:00Z',
  },
  {
    id: 'cu-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-cm', // Marcus Ray (assigned manager)
    access_type: 'staff_assignee',
    created_at: '2025-04-01T10:00:00Z',
  },
  {
    id: 'cu-4',
    agency_id: 'agency-1',
    client_id: 'client-2',
    user_id: 'user-cm', // Marcus Ray assigned
    access_type: 'staff_assignee',
    created_at: '2025-05-15T11:00:00Z',
  },
  {
    id: 'cu-5',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-team', // Chloe Zhao assigned
    access_type: 'staff_assignee',
    created_at: '2025-04-01T10:00:00Z',
  },
  {
    id: 'cu-6',
    agency_id: 'agency-1',
    client_id: 'client-3',
    user_id: 'user-team', // Chloe Zhao assigned
    access_type: 'staff_assignee',
    created_at: '2025-08-20T14:00:00Z',
  },
];

export const SEED_SOCIAL_ACCOUNTS: SocialAccount[] = [
  {
    id: 'sa-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'instagram',
    handle: '@luminaskinwellness',
    profile_name: 'Lumina Skin & Wellness',
    followers_count: 84200,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-04-10T12:00:00Z',
    last_synced_at: '2026-10-02T04:00:00Z',
  },
  {
    id: 'sa-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'tiktok',
    handle: '@luminaskincare',
    profile_name: 'Lumina Glow Tips',
    followers_count: 142500,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-05-01T10:00:00Z',
    last_synced_at: '2026-10-02T04:10:00Z',
  },
  {
    id: 'sa-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'facebook',
    handle: 'LuminaWellnessOfficial',
    profile_name: 'Lumina Skin Community',
    followers_count: 36900,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-04-10T12:30:00Z',
    last_synced_at: '2026-10-02T03:55:00Z',
  },
  {
    id: 'sa-4',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'linkedin',
    handle: 'lumina-skin-corp',
    profile_name: 'Lumina Skin Laboratories',
    followers_count: 12400,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-06-15T09:00:00Z',
    last_synced_at: '2026-10-02T04:15:00Z',
  },
  {
    id: 'sa-5',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'twitter_x',
    handle: '@LuminaBeauty',
    profile_name: 'Lumina Skin',
    followers_count: 24800,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-07-02T15:00:00Z',
    last_synced_at: '2026-10-02T04:00:00Z',
  },
  {
    id: 'sa-6',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'youtube',
    handle: 'LuminaSkinRadiance',
    profile_name: 'Lumina Skin Labs',
    followers_count: 48900,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-08-10T11:00:00Z',
    last_synced_at: '2026-10-02T04:20:00Z',
  },
  // Apex Fitness Gear
  {
    id: 'sa-7',
    agency_id: 'agency-1',
    client_id: 'client-2',
    platform_id: 'instagram',
    handle: '@apexfitnessgear',
    profile_name: 'Apex Fitness Gear',
    followers_count: 128400,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-05-20T10:00:00Z',
    last_synced_at: '2026-10-02T03:50:00Z',
  },
  {
    id: 'sa-8',
    agency_id: 'agency-1',
    client_id: 'client-2',
    platform_id: 'tiktok',
    handle: '@apex_heavy',
    profile_name: 'Apex Lifting Lab',
    followers_count: 295000,
    account_status: 'connected',
    is_mock: false,
    connected_at: '2025-06-01T14:00:00Z',
    last_synced_at: '2026-10-02T04:05:00Z',
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    name: 'Autumn Hydration Ritual 2026',
    goal: 'Drive 2,500 qualified leads and $120,000 direct sales for the Botanical Ceramide Cream relaunch.',
    budget: 18000,
    spent: 12450,
    status: 'active',
    start_date: '2026-09-01',
    end_date: '2026-10-31',
    created_at: '2026-08-15T09:00:00Z',
    updated_at: '2026-10-01T12:00:00Z',
  },
  {
    id: 'camp-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    name: 'Derm-Backed Sun Protection',
    goal: 'Educate on daily SPF routines with educational TikTok shorts and dermatologist live Q&A.',
    budget: 9500,
    spent: 9100,
    status: 'completed',
    start_date: '2026-06-01',
    end_date: '2026-08-31',
    created_at: '2026-05-20T10:00:00Z',
    updated_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'camp-3',
    agency_id: 'agency-1',
    client_id: 'client-2',
    name: 'Unstoppable Q4 PR Challenge',
    goal: 'Scale community user-generated content (UGC) with lifting PR submissions and ambassador sponsorships.',
    budget: 22000,
    spent: 15300,
    status: 'active',
    start_date: '2026-09-15',
    end_date: '2026-11-15',
    created_at: '2026-08-25T11:00:00Z',
    updated_at: '2026-10-01T15:00:00Z',
  },
];

export const SEED_SOCIAL_POSTS: SocialPost[] = [
  {
    id: 'post-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    platform_id: 'instagram',
    caption: 'When the seasons change, your lipid barrier asks for reinforcement. Our Botanical Ceramide Cream locks in dewiness for up to 72 hours without clogging pores. Tap link in bio to read our clinical trial results.',
    hashtags: ['#CleanSkincare', '#Ceramides', '#BarrierRepair', '#LuminaGlow', '#Dermatology'],
    media_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    media_type: 'image',
    status: 'PUBLISHED',
    published_at: '2026-10-01T14:00:00Z',
    scheduled_for: '2026-10-01T14:00:00Z',
    creator_id: 'user-cm',
    reviewer_id: 'user-admin',
    ai_generated: true,
    performance_metrics: {
      views: 18450,
      likes: 1240,
      shares: 310,
      comments: 84,
      clicks: 420,
      engagement_rate: 4.9,
    },
    created_at: '2026-09-28T10:00:00Z',
    updated_at: '2026-10-01T14:00:00Z',
  },
  {
    id: 'post-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    platform_id: 'tiktok',
    caption: '3 mistakes you are probably making when applying hyaluronic acid serum on dry skin. Mistake #2 is drying your skin out faster!',
    hashtags: ['#SkincareHacks', '#SkinBarrier', '#HyaluronicAcid', '#EstheticianTips', '#LuminaLabs'],
    media_url: 'https://images.unsplash.com/photo-1608248597359-009f485db586?w=800&auto=format&fit=crop&q=80',
    media_type: 'video',
    status: 'PUBLISHED',
    published_at: '2026-09-30T17:30:00Z',
    scheduled_for: '2026-09-30T17:30:00Z',
    creator_id: 'user-cm',
    reviewer_id: 'user-admin',
    ai_generated: true,
    performance_metrics: {
      views: 74200,
      likes: 6890,
      shares: 1420,
      comments: 312,
      clicks: 1150,
      engagement_rate: 6.8,
    },
    created_at: '2026-09-27T11:00:00Z',
    updated_at: '2026-09-30T17:30:00Z',
  },
  {
    id: 'post-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    platform_id: 'instagram',
    caption: 'Weekend Reset: Your evening ritual guide in 4 serene steps. Double tap if Sunday night skincare is non-negotiable in your house.',
    hashtags: ['#SundaySelfCare', '#NightSkincare', '#SkinRituals', '#WellnessRoutine'],
    media_url: 'https://images.unsplash.com/photo-1512290900672-1f5bebb1cf07?w=800&auto=format&fit=crop&q=80',
    media_type: 'carousel',
    status: 'SCHEDULED',
    scheduled_for: '2026-10-04T18:00:00Z',
    creator_id: 'user-cm',
    reviewer_id: 'user-cm',
    ai_generated: true,
    created_at: '2026-10-01T15:00:00Z',
    updated_at: '2026-10-02T02:00:00Z',
  },
  {
    id: 'post-4',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    platform_id: 'linkedin',
    caption: 'The science of micro-encapsulated actives: How Lumina R&D engineered a stable 15% Vitamin C formulation without oxidation risk. Read our patent announcement.',
    hashtags: ['#CosmeticChemistry', '#Biotech', '#BeautyInnovation', '#FormulationScience'],
    media_url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&auto=format&fit=crop&q=80',
    media_type: 'image',
    status: 'PENDING_REVIEW',
    creator_id: 'user-cm',
    ai_generated: true,
    created_at: '2026-10-02T03:30:00Z',
    updated_at: '2026-10-02T03:30:00Z',
  },
  {
    id: 'post-5',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'twitter_x',
    caption: 'Reminder: Glowing skin isn’t an overnight miracle, it’s cumulative consistency. Drink your water, wear your SPF, and protect your barrier. 🌿✨',
    hashtags: ['#SkinCareTip', '#DailyHabits'],
    media_type: 'text',
    status: 'APPROVED',
    scheduled_for: '2026-10-03T13:00:00Z',
    creator_id: 'user-cm',
    reviewer_id: 'user-cm',
    ai_generated: true,
    created_at: '2026-10-02T01:00:00Z',
    updated_at: '2026-10-02T02:45:00Z',
  },
  {
    id: 'post-6',
    agency_id: 'agency-1',
    client_id: 'client-1',
    platform_id: 'youtube',
    caption: 'Step-by-Step Lymphatic Facial Massage with Gua Sha & Cold-Pressed Rosehip Oil. Full 12-minute follow-along routine.',
    hashtags: ['#GuaShaRoutine', '#FacialMassage', '#NaturalGlow', '#LuminaChannel'],
    media_url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
    media_type: 'video',
    status: 'DRAFT',
    creator_id: 'user-cm',
    ai_generated: true,
    created_at: '2026-10-02T04:00:00Z',
    updated_at: '2026-10-02T04:00:00Z',
  },
  // Apex Fitness Post
  {
    id: 'post-7',
    agency_id: 'agency-1',
    client_id: 'client-2',
    campaign_id: 'camp-3',
    platform_id: 'instagram',
    caption: 'Heavy singles don’t care about excuses. The new Carbon-Grip Lifting Straps tested up to 1,000 lbs break-strength. Built for the lifters who leave zero doubt on the platform.',
    hashtags: ['#ApexHeavy', '#DeadliftPR', '#Powerlifting', '#StrengthCulture', '#LiftingStraps'],
    media_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&auto=format&fit=crop&q=80',
    media_type: 'image',
    status: 'PUBLISHED',
    published_at: '2026-10-01T16:00:00Z',
    scheduled_for: '2026-10-01T16:00:00Z',
    creator_id: 'user-cm',
    reviewer_id: 'user-admin',
    ai_generated: true,
    performance_metrics: {
      views: 34100,
      likes: 3120,
      shares: 680,
      comments: 184,
      clicks: 890,
      engagement_rate: 6.2,
    },
    created_at: '2026-09-29T12:00:00Z',
    updated_at: '2026-10-01T16:00:00Z',
  },
];

export const SEED_CONTENT_DRAFTS: ContentDraft[] = [
  {
    id: 'draft-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    title: 'Autumn Solstice Skincare Transition Guide',
    content_theme: 'Seasonal skin adaptation',
    raw_text: 'As ambient humidity drops, sebum production slows down while transepidermal water loss surges. Switch to occlusive lipids.',
    suggested_hashtags: ['#AutumnSkincare', '#LipidBarrier', '#HydrationRoutine'],
    platforms: ['instagram', 'tiktok', 'facebook'],
    created_by: 'user-cm',
    status: 'draft',
    created_at: '2026-10-01T16:00:00Z',
    updated_at: '2026-10-01T16:00:00Z',
  },
  {
    id: 'draft-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    title: 'Customer Spotlight: Maria’s 60-Day Barrier Recovery',
    content_theme: 'Social Proof / Case Study',
    raw_text: 'Before discovering Lumina, Maria struggled with recurrent redness and stinging after trying harsh acids. Here is her journey.',
    suggested_hashtags: ['#SkinTransformation', '#RealResults', '#SensitiveSkin'],
    platforms: ['instagram', 'tiktok'],
    created_by: 'user-cm',
    status: 'draft',
    created_at: '2026-10-02T02:00:00Z',
    updated_at: '2026-10-02T02:00:00Z',
  },
];

export const SEED_CONTENT_CALENDAR: ContentCalendarSlot[] = [
  {
    id: 'cal-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    post_id: 'post-1',
    scheduled_date: '2026-10-01',
    time_slot: '14:00',
    notes: 'Launch of Autumn Hydration campaign kickoff post',
    created_at: '2026-09-28T10:00:00Z',
  },
  {
    id: 'cal-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    post_id: 'post-3',
    scheduled_date: '2026-10-04',
    time_slot: '18:00',
    notes: 'Prime Sunday engagement window for wellness audience',
    created_at: '2026-10-01T15:00:00Z',
  },
  {
    id: 'cal-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    post_id: 'post-5',
    scheduled_date: '2026-10-03',
    time_slot: '13:00',
    notes: 'Mid-day motivation and hydration reminder',
    created_at: '2026-10-02T01:00:00Z',
  },
];

export const SEED_SEO_PROJECTS: SeoProject[] = [
  {
    id: 'seo-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    domain: 'luminaskin.example.com',
    health_score: 93,
    organic_traffic_monthly: 48600,
    created_at: '2025-04-15T09:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'seo-2',
    agency_id: 'agency-1',
    client_id: 'client-2',
    domain: 'apexfitness.example.com',
    health_score: 88,
    organic_traffic_monthly: 62400,
    created_at: '2025-05-25T11:00:00Z',
    updated_at: '2026-10-01T08:00:00Z',
  },
];

export const SEED_SEO_KEYWORDS: SeoKeyword[] = [
  {
    id: 'kw-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    project_id: 'seo-1',
    keyword: 'botanical ceramide moisturizer',
    current_position: 2,
    previous_position: 5,
    search_volume: 14800,
    difficulty: 46,
    target_url: 'https://luminaskin.example.com/products/ceramide-cream',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'kw-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    project_id: 'seo-1',
    keyword: 'best clean skincare for sensitive skin',
    current_position: 4,
    previous_position: 7,
    search_volume: 27500,
    difficulty: 62,
    target_url: 'https://luminaskin.example.com/collections/sensitive',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'kw-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    project_id: 'seo-1',
    keyword: 'how to repair skin lipid barrier',
    current_position: 3,
    previous_position: 8,
    search_volume: 18200,
    difficulty: 54,
    target_url: 'https://luminaskin.example.com/journal/barrier-guide',
    updated_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'kw-4',
    agency_id: 'agency-1',
    client_id: 'client-1',
    project_id: 'seo-1',
    keyword: 'non comedogenic mineral sunscreen spf 50',
    current_position: 6,
    previous_position: 6,
    search_volume: 32000,
    difficulty: 71,
    target_url: 'https://luminaskin.example.com/products/solarshield-spf50',
    updated_at: '2026-10-01T08:00:00Z',
  },
];

export const SEED_SEO_ISSUES: SeoIssue[] = [
  {
    id: 'iss-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    project_id: 'seo-1',
    title: 'Missing canonical tag on seasonal promo collection variants',
    severity: 'warning',
    category: 'meta_tags',
    status: 'open',
    ai_recommendation: 'Add self-referencing canonical tag `<link rel="canonical" href="..."/>` to all pagination and filter parameter URLs to avoid keyword cannibalization.',
    created_at: '2026-09-28T09:00:00Z',
  },
  {
    id: 'iss-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    project_id: 'seo-1',
    title: 'Hero banner images on mobile lack AVIF/WebP compression',
    severity: 'error',
    category: 'performance',
    status: 'resolved',
    ai_recommendation: 'Serve modern responsive `srcset` with WebP formats to shave 420ms off Largest Contentful Paint (LCP).',
    created_at: '2026-09-15T10:00:00Z',
    resolved_at: '2026-09-29T14:00:00Z',
  },
  {
    id: 'iss-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    project_id: 'seo-1',
    title: 'Schema.org Product & Review structured data missing priceValidUntil',
    severity: 'notice',
    category: 'crawlability',
    status: 'open',
    ai_recommendation: 'Inject `priceValidUntil: "2027-12-31"` to retain Google Merchant rich snippet stars in organic search results.',
    created_at: '2026-10-01T12:00:00Z',
  },
];

export const SEED_LEADS: Lead[] = [
  {
    id: 'lead-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    name: 'Jessica Thorne',
    email: 'jess.thorne@gmail.com',
    phone: '+1 415-555-0192',
    source: 'Instagram Ad',
    status: 'converted',
    lead_value: 185.00,
    created_at: '2026-09-29T11:20:00Z',
  },
  {
    id: 'lead-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    name: 'Maya Lin',
    email: 'maya.lin@outlook.com',
    phone: '+1 650-555-8831',
    source: 'TikTok Organic',
    status: 'qualified',
    lead_value: 240.00,
    created_at: '2026-09-30T15:45:00Z',
  },
  {
    id: 'lead-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    name: 'Claire Dupont',
    email: 'cdupont@wellnessstudio.co',
    phone: '+1 212-555-4029',
    source: 'Google Search',
    status: 'converted',
    lead_value: 850.00,
    created_at: '2026-10-01T09:10:00Z',
  },
  {
    id: 'lead-4',
    agency_id: 'agency-1',
    client_id: 'client-1',
    name: 'Sophia Patel',
    email: 'spatel@techbeauty.io',
    phone: '+1 312-555-7714',
    source: 'LinkedIn InMail',
    status: 'new',
    lead_value: 450.00,
    created_at: '2026-10-02T02:15:00Z',
  },
];

export const SEED_SALES: Sale[] = [
  {
    id: 'sale-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    lead_id: 'lead-1',
    amount: 185.00,
    currency: 'USD',
    channel: 'Instagram Direct Checkout',
    converted_at: '2026-09-29T14:30:00Z',
  },
  {
    id: 'sale-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    lead_id: 'lead-3',
    amount: 850.00,
    currency: 'USD',
    channel: 'Shopify Store (Organic Search)',
    converted_at: '2026-10-01T11:00:00Z',
  },
  {
    id: 'sale-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    campaign_id: 'camp-1',
    amount: 320.00,
    currency: 'USD',
    channel: 'TikTok Shop Referral',
    converted_at: '2026-10-01T16:20:00Z',
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: 'task-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    assigned_to: 'user-cm',
    title: 'Review Lumina Autumn Carousel Copy with Brand Director',
    description: 'Verify ingredient percentages in slide 3 before final approval for Sunday slot.',
    priority: 'high',
    status: 'in_progress',
    due_date: '2026-10-03',
    created_at: '2026-10-01T09:00:00Z',
  },
  {
    id: 'task-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    assigned_to: 'user-team',
    title: 'Implement canonical tags fix on collection URLs',
    description: 'Work with Shopify developer to patch parameter URL duplication.',
    priority: 'medium',
    status: 'todo',
    due_date: '2026-10-05',
    created_at: '2026-10-01T14:00:00Z',
  },
];

export const SEED_REPORTS: Report[] = [
  {
    id: 'rep-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    title: 'September 2026 Comprehensive Agency Growth Review',
    report_type: 'monthly',
    period_start: '2026-09-01',
    period_end: '2026-09-30',
    summary: 'Delivered +34% follower expansion across TikTok and Instagram. Organic revenue touched $42,800 with 4.9% overall engagement.',
    metrics_snapshot: {
      new_followers: 14200,
      total_reach: 489000,
      leads_generated: 168,
      sales_revenue: 42800,
      top_performing_platform: 'TikTok',
    },
    pdf_url: '#download-pdf-sample',
    created_at: '2026-10-01T08:00:00Z',
  },
  {
    id: 'rep-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    title: 'Q3 Social Media Engagement & Sentiment Audit',
    report_type: 'social',
    period_start: '2026-07-01',
    period_end: '2026-09-30',
    summary: 'Customer sentiment registered at 96.4% positive. Video save rate increased by 2.4x following short-form educational pivots.',
    metrics_snapshot: {
      total_views: 1840000,
      comments: 6420,
      share_count: 14800,
      sentiment_score: 96.4,
    },
    created_at: '2026-10-01T09:30:00Z',
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    agency_id: 'agency-1',
    user_id: 'user-cm',
    title: 'New Post Pending Review',
    message: 'Post "The science of micro-encapsulated actives" for Lumina Skin is ready for final review.',
    type: 'info',
    is_read: false,
    link_url: '/content/approval-queue',
    created_at: '2026-10-02T03:30:00Z',
  },
  {
    id: 'notif-2',
    agency_id: 'agency-1',
    user_id: 'user-admin',
    title: 'Milestone: $1,355 in Tracked Sales Today',
    message: 'Lumina Skin Autumn Hydration campaign surpassed 120 leads.',
    type: 'success',
    is_read: false,
    link_url: '/analytics',
    created_at: '2026-10-01T18:00:00Z',
  },
  {
    id: 'notif-3',
    agency_id: 'agency-1',
    user_id: 'user-cm',
    title: 'Post Published Successfully',
    message: 'Instagram post for Lumina Skin published on schedule.',
    type: 'success',
    is_read: true,
    link_url: '/content/calendar',
    created_at: '2026-10-01T14:00:00Z',
  },
];

export const SEED_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-agency-1',
    agency_id: 'agency-1',
    plan_name: 'Nexus Enterprise OS',
    billing_interval: 'monthly',
    price: 999.00,
    status: 'active',
    current_period_end: '2026-10-31T23:59:59Z',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'sub-client-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    plan_name: 'OmniGrowth Retainer (Lumina Skin)',
    billing_interval: 'monthly',
    price: 8500.00,
    status: 'active',
    current_period_end: '2026-10-31T23:59:59Z',
    created_at: '2025-04-01T10:00:00Z',
  },
  {
    id: 'sub-client-2',
    agency_id: 'agency-1',
    client_id: 'client-2',
    plan_name: 'Apex Scale Retainer',
    billing_interval: 'monthly',
    price: 6500.00,
    status: 'active',
    current_period_end: '2026-10-31T23:59:59Z',
    created_at: '2025-05-15T11:00:00Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-admin',
    user_email: 'elena@nexussocial.com',
    action: 'LOGIN',
    entity_type: 'AUTH_SESSION',
    details: { device: 'MacBook Pro', browser: 'Chrome 128', ip: '198.51.100.4' },
    ip_address: '198.51.100.4',
    created_at: '2026-10-02T03:00:00Z',
  },
  {
    id: 'log-2',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-cm',
    user_email: 'marcus@nexussocial.com',
    action: 'CONTENT_GENERATION',
    entity_type: 'AI_AGENT',
    entity_id: 'tool_generate_content_calendar',
    details: { prompt: 'Generate 7-day social calendar for Lumina Skin hydration theme', tools: ['generate_content_calendar'] },
    ip_address: '198.51.100.12',
    created_at: '2026-10-02T03:15:00Z',
  },
  {
    id: 'log-3',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-cm',
    user_email: 'marcus@nexussocial.com',
    action: 'APPROVAL',
    entity_type: 'SOCIAL_POST',
    entity_id: 'post-5',
    details: { status: 'APPROVED', previous_status: 'PENDING_REVIEW' },
    ip_address: '198.51.100.12',
    created_at: '2026-10-02T02:45:00Z',
  },
  {
    id: 'log-4',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-cm',
    user_email: 'marcus@nexussocial.com',
    action: 'PUBLISHING',
    entity_type: 'SOCIAL_POST',
    entity_id: 'post-1',
    details: { platform: 'instagram', external_id: 'ig_94829104', reached: 18450 },
    ip_address: '198.51.100.12',
    created_at: '2026-10-01T14:00:00Z',
  },
  {
    id: 'log-5',
    agency_id: 'agency-1',
    client_id: 'client-1',
    user_id: 'user-admin',
    user_email: 'elena@nexussocial.com',
    action: 'CUSTOMER_CREATE',
    entity_type: 'CLIENT',
    entity_id: 'client-1',
    details: { client_name: 'Lumina Skin & Wellness', monthly_retainer: 8500 },
    ip_address: '198.51.100.4',
    created_at: '2025-04-01T10:00:00Z',
  },
];
